server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "User management Pragma"
appVersion: "1.0.0"

